name: Ejecuta cada domingo index.mjs (scrape de dbd wiki + guardar datos en supabase)
on:
  schedule:
    - cron: '0 0 * * 0'  # Ejecuta cada domingo a medianoche
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: node index.mjs
